services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
    volumes:
      - ./config:/config
    ports:
      - "9696:9696"
    restart: unless-stopped
    
    labels:
      - homepage.group=Media
      - homepage.name=Prowlarr
      - homepage.icon=prowlarr.png
      - homepage.href=IP PROWLARR
      - homepage.description=Gerenciador de indexadores