services:
  filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: filebrowser
    restart: unless-stopped

    ports:
      - "8082:80"

    volumes:
      - ${MEDIA_DIR:-/mnt/media}:/srv
      - ${DATA_DIR:-/opt/media-server}/filebrowser/database:/database
      - ${DATA_DIR:-/opt/media-server}/filebrowser/config:/config


