networks:
  forgejo:

services:
  server:
    image: codeberg.org/forgejo/forgejo:16
    container_name: forgejo

    environment:
      - USER_UID=1000
      - USER_GID=1000
      - FORGEJO__server__SSH_PORT=222

    restart: unless-stopped

    networks:
      - forgejo

    volumes:
      - ${DATA_DIR:-/opt/media-server}/forgejo/data:/data
      - /etc/localtime:/etc/localtime:ro

    ports:
      - "3044:3000"
      - "222:22"

